export const featuresSectionSubTitleKeywords = [
    "Acest proiect",
    "combinație armonioasă",
    "sport",
    "educație",
    "Baschetul",
    "punct central",
    "competitiv",
    "învățăminte esențiale",
    "colaborare",
    " perseverență",
    "depășirea obstacolelor",
];

export const fifthSectionSubTitleKeywords = [
    "2016",
    "președinte",
    "Asociației",
    "Alege Să Trăiești",
    "colaborare",
    "Agenția Națională de Antidrog",
    "comisar",
    "Dan Prică",
    "Statele Unite",
    "Crossroads",
    "Tennessee",
    "antrenorul",
    "baschet",
    "Phil Pippenger",
    "proiectul",
    "sportiv",
    "educațional",
    "Elevate Your Life",
];

export const fifthSectionSecondSubTitleKeywords = [
    "Baptiștii",
    "ramură",
    "creștinismul protestant",
    "accentul",
    "botezul credinței",
    "scufundare",
    "mărturisesc",
    "credința personală",
    "autoritatea supremă",
    "Biblia",
    "viața credincioșilor",
    "bisericii",

];
export const fifthSectionThirdSubTitleKeywords = [
    "mântuirea",
    "har",
    "credința",
    "Isus Hristos",
    "promovăm",
    "autonomia",
    "bisericii locale",
    "libertatea religioasă",
    "separarea",
    "biserică",
    "stat"
];

export const thirdSectionSubTitleKeywords = [
    "copii",
    "tineri",
    "școală",
    "vicii",
    "comportamentul",
    "părinți",
    "profesori",
    "colegii",
    "proiect",
    "comunitate",
    "antrenori",
    "parteneriat",
    "diferență",
    "benefică",
    "comunității",
];

export const lessonsKeywords = [
    "coechipieri",
    "anturajul",
    "prietenii",
    "reprezintă",
    "sprijinul",
    "colaborarea",
    "necesare",
    "adversarii",
    "simbolizează",
    "obstacolele",
    "tentațiile",
    "depășim",
    "împlini",
    "visurile",
    "lumea baschetului",
    "copiii",
    "învăța",
    "abilități sportive",
    "valori fundamentale",
    "ghida",
    "parcursul vieții",

    "Acest",
    "proiect",
    "constantă",
    "viața noastră",
    "singur an",
    "impus",
    "determinat",
    "adaptăm",
    "antrenori",
    "dedicat",
    "pasiune",
    "acestui proiect",
    "antrenamente",
    "întâlniri periodice",
    "ședințe tehnice",
    "sesiuni de dezvoltare personală",

    "Anul trecut",
    "2023",
    "decid",
    "ridicăm ștacheta",
    "următorul nivel",
    "simplu proiect",
    "Parcul Victoria",
    "2016",
    "înființarea",
    "Clubului Sportiv",
    "Călărași Warriors",
    "150 de copii",
    "băieți și fete",
    "9 și 19 ani",
    "diverse medii sociale",

    "ultimilor 4 ani",
    "atletism de performanță",
    "instructor de fitness",
    "culturism",
    "peste 300 de tineri",
    "băieți și fete",
    "instituțiile militare",
    "Poliție",
    "Jandarmerie",
    "Pompieri",
    "Școlile",
    "Academiile Militare",
    "eforturi",
    "voluntar",
    "dorința",
    "formarea",
    "viitoarei generații",
    "viitor mai bun",
    "comunitatea noastră",

    "oamenii",
    "cu adevărat o artă",
    "diferiți",
    "nevoile",
    "diverse",
    "viața individului",
    "social",
    "material",
    "Dumnezeu",
    "flămând",
    "termenii pâinii",
    "educațional",
    "sportiv"
];
