

// Features section keywords for highlighting
export const lessonsKeywords = [

    "coechipieri",
    "anturajul",
    "prietenii",
    "reprezintă",
    "sprijinul",
    "colaborarea",
    "necesare",
    "adversarii",
    "simbolizează",
    "obstacolele",
    "tentațiile",
    "depășim",
    "împlini",
    "visurile",
    "lumea baschetului",
    "copiii",
    "învăța",
    "abilități sportive",
    "valori fundamentale",
    "ghida",
    "parcursul vieții",

    "Acest",
    "proiect",
    "constantă",
    "viața noastră",
    "singur an",
    "impus",
    "determinat",
    "adaptăm",
    "antrenori",
    "dedicat",
    "pasiune",
    "acestui proiect",
    "antrenamente",
    "întâlniri periodice",
    "ședințe tehnice",
    "sesiuni de dezvoltare personală",

    "Anul trecut",
    "2023",
    "decid",
    "ridicăm ștacheta",
    "următorul nivel",
    "simplu proiect",
    "Parcul Victoria",
    "2016",
    "înființarea",
    "Clubului Sportiv",
    "Călărași Warriors",
    "150 de copii",
    "băieți și fete",
    "9 și 19 ani",
    "diverse medii sociale",

    "ultimilor 4 ani",
    "atletism de performanță",
    "instructor de fitness",
    "culturism", ,
    "peste 300 de tineri",
    "băieți și fete",
    "instituțiile militare",
    "Poliție",
    "Jandarmerie",
    "Pompieri",
    "Școlile",
    "Academiile Militare",
    "eforturi",
    "voluntar",
    "dorința",
    "formarea",
    "viitoarei generații",
    "viitor mai bun",
    "comunitatea noastră",

    "oamenii",
    "cu adevărat o artă",
    "diferiți",
    "nevoile",
    "diverse",
    "viața individului",
    "social",
    "material",
    "Dumnezeu",
    "flămând",
    "termenii pâinii",
    "educațional",
    "sportiv"
];
