// Features section keywords for highlighting
export const implementationMethodsKeywords = [
    "program educațional",
    "valori",
    "principii fundamentale",
    "cadrul",
    "activităților sportive",
    "sesiuni de instruire",
    "fair-play",
    " echipă",
    "dezvoltare personală",
    "prevenirea",
    "combaterea",
    "delicvenței juvenile",
    "antrenori",
    "părinți",
    "sportivi",
    "elevi",
    "comunitate",

    "sesiuni de consiliere",
    "cadre didactice",
    "membrii comunității",
    "călărășene",

    "sport",
    "antrenorii",
    "părinții",
    "sportivii",
    "valorile specifice",
    "comunității",
    "activităților sportive",


    "activitățile sportive",
    "toate categoriile de vârstă",
    "niveluri de abilitate",

    "programe speciale",
    "copii",
    "adolescenți",
    "adulți",
    "seniori",
    "toată comunitatea",
    "se simtă inclusă",
    "legătură puternică",
    "dezvoltarea personală",
    " sportivă",

    " școala",
    "liceul",
    "primăria",
    "biserica",
    "poliția",
    "organizații",
    "scop comun",
    "activitățile sportive",
    "programele educaționale",
    "comunitate",
    "voluntariatul",
    "impactul",
    "participarea",
    "completăm",
    "unii pe ceilalți",
    "ajutăm reciproc",

    "evenimente sportive",
    "regulate",
    "aduce oamenii împreună",
    "competiții",
    "jocuri amicale",
    "serii de exerciții",
    "proiecte de voluntariat",
    "tematică sportivă",
    "fiecare categorie",
    "de disciplină sportivă",
    "regim de parteneriat",

    "platforme online",
    "radio",
    "televiziune",
    "instagram",
    "facebook",
    "offline",
    "comunicarea",
    "participarea comunității",
    "părinți din comunitate",
    "mai bine informați",
    "discipline sportive",
    "copiii lor",

    "sisteme de recunoaștere",
    "recompensare",
    "membrii comunității",
    "implicați activ",
    "activitățile sportive",
    "crește",
    "motivarea",
    "implicarea",

];
